# Generated by Django 6.0 on 2026-02-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_if',
            new_name='transaction_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
