# Generated by Django 6.0 on 2026-02-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_transaction_if_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pidx',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
