# Generated by Django 6.0 on 2026-02-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_deliveryperson_approved_at_deliveryperson_is_active_and_more'),
        ('store', '0015_payment_purchase_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.deliveryperson'),
        ),
    ]
