# Generated by Django 6.0 on 2026-02-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deliveryperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryperson',
            old_name='las_location',
            new_name='last_location',
        ),
    ]
